### ISSUE TITLE
[Bug]: Crash on adding account

### ISSUE THREAD

**Issue by AndrewGBest** [Switch-Bros/SteamLibraryManager#11]
### SLM Version

v1.3.5

### Install method

AppImage

### Linux Distro

CachyOS

### Steam installation

Native

### Steam Deck?

None

### What happened?

App crashes when hitting continue after selecting account.

### Steps to reproduce

Use any of the options to select your steam account
hit continue.

### Log file

```shell
No log file is generated at that location, here is the terminal output.

❯ /home/andrew/Downloads/SteamLibraryManager-x86_64.AppImage
06:35:56 [INFO] steamlibmgr.desktop: Installing desktop integration...
06:35:56 [INFO] steamlibmgr.desktop: Desktop file written: /home/andrew/.local/share/applications/io.github.switch_bros.SteamLibraryManager.desktop
06:35:56 [INFO] steamlibmgr.desktop: Icon copied: /home/andrew/.local/share/icons/hicolor/scalable/apps/io.github.switch_bros.SteamLibraryManager.svg
06:35:57 [INFO] steamlibmgr: No user profile configured. Starting setup...
06:35:57 [INFO] steamlibmgr.account_scanner: Scanning Steam accounts in: /home/andrew/.local/share/Steam/userdata
06:35:57 [INFO] steamlibmgr.account_scanner: Found account: 48416029 -> SteamID64: 76561198008681757
06:35:57 [INFO] steamlibmgr.account_scanner:   -> Display name: Andrew
06:35:57 [INFO] steamlibmgr.account_scanner: Total accounts found: 1
Traceback (most recent call last):
  File "steam_library_manager/main.py", line 217, in <module>
  File "steam_library_manager/main.py", line 180, in main
AttributeError: 'ProfileSetupDialog' object has no attribute 'selected_steam_id_64'
[PYI-3583677:ERROR] Failed to execute script 'main' due to unhandled exception!
```

**Comment by HeikesFootSlave** [comment]
Can you confirm that it works with new 1.3.6 Version?

**Comment by PoorPocketsMcNewHold** [comment]
Can confirm it fixed it for me.

**Comment by HeikesFootSlave** [comment]
Solved

**Comment by GoAwayNow** [comment]
Sorry, haven't had much time around my computer. It worked.
